context("Handling palette functions")

test_that("property methods can be applied to functions", {
    rampFunction <- colorRampPalette(c("red", "blue"))
    
    # The distinction is in the parentheses here: in one case lightness() is called on colours generated by the colour ramp; in the other, the ramp function is wrapped by lightness() and then called
    expect_equal(lightness(rampFunction(5L)), lightness(rampFunction)(5L))
    expect_equal(lightness(rampFunction(5L),50), lightness(rampFunction,50)(5L))
    
    skip_if_not_installed("ggplot2")
    
    library(ggplot2)
    
    data <- data.frame(sex=c("M","M","F","F"), age=c(23,34,28,26), height=c(180,168,159,170))
    plot <- ggplot(data, aes(x=age,y=height,colour=sex)) + geom_point() + lightness(scale_colour_viridis_d(), 50)
    
    # This relies on scales::viridis_pal (at time of writing) agreeing with our viridis scale, but this seems less fragile than assuming that scales and ggplot2 continue to interact the way they do now (and adding another suggested dependency)
    expect_true(all(layer_data(plot)$colour %in% lightness(gradient("viridis",2), 50)))
})
