context("Handling palette functions")

test_that("property methods can be applied to functions", {
    rampFunction <- colorRampPalette(c("red", "blue"))
    
    # The distinction is in the parentheses here: in one case lightness() is called on colours generated by the colour ramp; in the other, the ramp function is wrapped by lightness() and then called
    expect_equal(lightness(rampFunction(5L)), lightness(rampFunction)(5L))
    expect_equal(lightness(rampFunction(5L),50), lightness(rampFunction,50)(5L))
    
    skip_if_not_installed("ggplot2")
    
    
})
